#define MAJOR_VERSION	26
#define MINOR_VERSION	0
#define MICRO_VERSION	3
#define BUILD_VERSION	0

#define QUOTE_(x)		#x
#define QUOTE(x)		QUOTE_(x)

#define VERSION_STRING	QUOTE(MAJOR_VERSION.MINOR_VERSION.MICRO_VERSION.BUILD_VERSION)
#define VERSION_STRING_W	_T(QUOTE(MAJOR_VERSION.MINOR_VERSION.MICRO_VERSION.BUILD_VERSION))

#define BUILD_DATE		"06/04/2026 00:00:00"
#define BUILD_DATE_STRING	_T(QUOTE(BUILD_DATE))
